---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoom-deployment
  namespace: default
  annotations:
    kubernetes.io/change-cause: "Updated the version from latest to 1.26 to downgrade the application"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoom
  template:
    metadata:
      labels:
        app: zoom
    spec:
      containers:
        - name: zoom-container
          image: sundarapandian1510/zoom:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: zoom-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: zoom
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
